pipeline { 
    environment { 
        repository = "seongguk92/jenkinsexample"  //docker hub id와 repository 이름
        DOCKERHUB_CREDENTIALS = credentials('Docker-Hub-ID') // jenkins에 등록해 놓은 docker hub credentials 이름
        dockerImage = '' 
    }
    agent any 
    stages { 
        stage('Building our image') { 
            steps { 
                script { 
                    sh "cp /var/lib/jenkins/workspace/seongguk92_jenkins_project/build/libs/sue-member-0.0.1-SNAPSHOT.war /var/lib/jenkins/workspace/pipeline/" // war 파일을 현재 위치로 복사 
                    dockerImage = docker.build repository + ":$BUILD_NUMBER" 
                }
            } 
        } 
    }
}