pipeline { 
    environment { 
        repository = "seongguk92/jenkinsexample"  //docker hub id와 repository 이름
        DOCKERHUB_CREDENTIALS = credentials('Docker-Hub-ID') // jenkins에 등록해 놓은 docker hub credentials 이름
        dockerImage = '' 
    }
    agent any 
    stages { 
        stage('Building our image') { 
            steps { 
                script { 
                    dockerImage = sudo docker.build repository + ":$BUILD_NUMBER" 
                }
            } 
        } 
        stage('Login'){
          steps{
              sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin' // docker hub 로그인
          }
        }
    }
}